language: node_js
node_js:
  - stable

before_install:
  - cd reference-implementation
script:
  - npm test
  - cd .. && bash ./deploy.sh

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: always

env:
  global:
    - ENCRYPTION_LABEL: "d49f480b94f1"
    - COMMIT_AUTHOR_EMAIL: "d@domenic.me"
