language: node_js
node_js:
  - stable

before_install:
  - cd reference-implementation
script:
  - npm run lint
  - npm test

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: always
